import { BarChart3, CalendarDays, Instagram, Sparkles, TrendingUp, Users } from "lucide-react";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { SyncButton } from "./sync-button";

const cards=[{label:"Alcance",value:"—",icon:Users,note:"Importe os dados da conta"},{label:"Visualizações",value:"—",icon:TrendingUp,note:"Dados do período"},{label:"Interações",value:"—",icon:BarChart3,note:"Curtidas, comentários, compartilhamentos e salvamentos"},{label:"Conteúdos",value:"—",icon:Instagram,note:"Posts, Reels e outros formatos"}];

export default async function Home(){
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">INSTAGRAM ANALYTICS</p><h1>Seu conteúdo. Seus números. Suas decisões.</h1><p className="subtitle">Entre no painel para conectar sua conta profissional do Instagram e acompanhar sua evolução.</p><a className="connect" href="/login">Entrar no Analytics</a></section></main>;

  return <main className="shell"><header className="topbar"><div><p className="eyebrow">INSTAGRAM ANALYTICS</p><h1>Seu conteúdo. Seus números. <span>Suas decisões.</span></h1><p className="subtitle">Um painel para descobrir quais conteúdos realmente performam e por quê.</p></div><a className="connect" href="/api/instagram/login"><Instagram size={18}/>Conectar Instagram</a></header><section className="toolbar"><div className="period"><CalendarDays size={17}/><span>Período</span><select defaultValue="30"><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="365">Último ano</option><option value="custom">Personalizado</option></select></div><div className="toolbar-actions"><div className="status"><span className="dot"/>Sincronização diária</div><SyncButton /></div></section><section className="cards">{cards.map(({label,value,icon:Icon,note})=><article className="card" key={label}><div className="card-icon"><Icon size={19}/></div><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}</section><section className="empty"><div className="empty-icon"><Sparkles size={24}/></div><h2>Vamos começar pelos seus dados reais</h2><p>Conecte sua conta profissional do Instagram. O sistema vai importar os conteúdos e as métricas que a API disponibilizar e guardar snapshots para construir seu histórico.</p><a className="connect secondary" href="/api/instagram/login">Conectar conta profissional</a></section></main>
}